"""Added wg_user table

Revision ID: b461010133c2
Revises: 1e351e1f769d
Create Date: 2022-03-22 11:40:40.307622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b461010133c2'
down_revision = '1e351e1f769d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('public_key', sa.String(), nullable=True),
    sa.Column('private_key', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wg_user_id'), 'wg_user', ['id'], unique=False)
    op.create_index(op.f('ix_wg_user_name'), 'wg_user', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wg_user_name'), table_name='wg_user')
    op.drop_index(op.f('ix_wg_user_id'), table_name='wg_user')
    op.drop_table('wg_user')
    # ### end Alembic commands ###
